In [35]:
import numpy as np

# Step 1 : Read the Data!

In [36]:
data_file="/content/makeSenseOfCensus.csv"

# Loading the data

In [37]:

data = np.genfromtxt(data_file, delimiter=",", skip_header=1)
print("\nData:\n\n ", data)



Data:

  [[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]


# Printing the type of data

In [38]:
print("\nType of data: \n\n\n", type(data))


Type of data: 


 <class 'numpy.ndarray'>


# Step 2 : Append the Data

In [39]:
new_record = [[50,9,4,1,0,0,40,0]]

## Append 'new_record' (given) to 'data' using "np.concatenate()"

In [40]:
final_data=np.concatenate((data,new_record))

In [41]:
final_data 

array([[39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       [38.,  9.,  4., ...,  0., 40.,  0.],
       ...,
       [40., 10.,  4., ...,  0., 40.,  0.],
       [39., 13.,  4., ...,  0., 50.,  1.],
       [50.,  9.,  4., ...,  0., 40.,  0.]])

# Step 3 : Check if it's a young country or old country

 Create a new array called 'age' by taking only age column(age is the column with index 0) of 'census' array.

In [42]:
age= final_data[:,0]
age

array([39., 50., 38., ..., 40., 39., 50.])

Find the max age and store it in a variable called 'max_age'.



In [81]:
max_age= (age.max())
print("Maximum Age is ",max_age)

Maximum Age is  90.0


Find the min age and store it in a variable called 'min_age'.

In [80]:
min_age= age.min()
print('minimum age is',min_age)

minimum age is 17.0


Find the mean of the age and store it in a variable called 'age_mean'.

In [45]:
age_mean = age.mean()
print(age_mean)

38.06293706293706


Find the standard deviation of the age and store it in a variable called 'age_std'

In [46]:
age_std = age.std()
print(age_std)

13.341478176165857


# Step 4: Let's check the country's race distribution to identify the minorities

Create four different arrays by subsetting 'census' array by Race column(Race is the column with index 2) and save them in 'race_0','race_1', 'race_2', 'race_3' and 'race_4' respectively(Meaning: Store the array where 'race'column has value 0 in 'race_0', so on and so forth)

In [47]:
final_data [final_data[:,2]==0]

array([[34.,  4.,  0.,  1.,  0.,  0., 45.,  0.],
       [35., 10.,  0.,  0.,  0.,  0., 40.,  0.],
       [60.,  6.,  0.,  0.,  0.,  0., 10.,  0.],
       [51.,  9.,  0.,  1.,  0.,  0., 40.,  0.],
       [25., 10.,  0.,  0.,  0.,  0., 20.,  0.],
       [20.,  9.,  0.,  1.,  0.,  0., 48.,  0.],
       [23., 10.,  0.,  0.,  0.,  0., 25.,  0.],
       [29.,  9.,  0.,  1.,  0.,  0., 40.,  0.],
       [27., 12.,  0.,  1.,  0.,  0., 40.,  0.],
       [31., 12.,  0.,  0.,  0.,  0., 40.,  0.]])

Store the length of the above created arrays in 'len_0', 'len_1','len_2', 'len_3' and 'len_4' respectively

In [48]:
race_0=final_data[final_data[:,2]==0]

In [49]:
race_1=final_data[final_data[:,2]==1]

In [50]:
race_2=final_data[final_data[:,2]==2]

In [51]:
race_3=final_data[final_data[:,2]==3]

In [52]:
race_4=final_data[final_data[:,2]==4]

Find out which is the race with the minimum no. of citizens

In [53]:
len_0=len(race_0)
len_0

10

In [54]:
len_1=len(race_1)
print(len_1)
len_2=len(race_2)
len_3=len(race_3)
len_4=len(race_4)

27


Find out which is the race with the minimum no. of citizens

In [55]:
min_citizen= min(len_0,len_1,len_2,len_3,len_4)
print(min_citizen)

6


Store the number associated with the minority race in a variable called 'minority_race'(For eg: if "len(race_5)" is the minimum, store 5 in 'minority_race' because that is the index of the race having the least no. of citizens )

In [56]:
if min_citizen==len_0:
  print("Race_0 has minimum No of citizen")
elif min_citizen==len_1:
  print("Race_1 has minimum No of citizen")
elif min_citizen==len_2:
  print("Race_2 has minimum No of citizen")
elif min_citizen==len_3:
  print("Race_3 has minimum No of citizen")
else:
  print("Race_4 has minimum No of citizen")


Race_3 has minimum No of citizen


Store the number associated with the minority race in a variable called 'minority_race'(For eg: if "len(race_5)" is the minimum, store 5 in 'minority_race' because that is the index of the race having the least no. of citizens )

In [57]:
if min_citizen==len_0:
  minority_race=0 
elif min_citizen==len_1:
  minority_race=1
elif min_citizen==len_2:
  minority_race=2
elif min_citizen==len_3:
  minority_race=3
else:
  minority_race=4
print("Minority Race: ",minority_race)

Minority Race:  3


# Step 5: As per govt. records citizens above 60 should not work more than 25 hours a week. Let us check if the policy is in place

a.Create a new subset array called 'senior_citizens' by filtering 'census' according to age>60 (age is the column with index 0)

[Row,Columns]  :

In [61]:
#from age column, filter out age data > 60 
senior_citizens = final_data[final_data[:,0]>60]
print(senior_citizens)

[[7.9000e+01 1.0000e+01 4.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00
  2.0000e+01 0.0000e+00]
 [6.7000e+01 6.0000e+00 4.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00
  2.0000e+00 0.0000e+00]
 [7.6000e+01 1.4000e+01 4.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00
  4.0000e+01 1.0000e+00]
 [6.1000e+01 9.0000e+00 4.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00
  4.0000e+01 0.0000e+00]
 [7.0000e+01 1.0000e+01 4.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00
  4.0000e+01 0.0000e+00]
 [6.4000e+01 7.0000e+00 4.0000e+00 1.0000e+00 0.0000e+00 2.1790e+03
  4.0000e+01 0.0000e+00]
 [7.1000e+01 1.0000e+01 2.0000e+00 1.0000e+00 0.0000e+00 1.8160e+03
  2.0000e+00 0.0000e+00]
 [6.8000e+01 2.0000e+00 4.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00
  2.0000e+01 0.0000e+00]
 [6.6000e+01 1.1000e+01 4.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00
  2.0000e+01 0.0000e+00]
 [6.4000e+01 2.0000e+00 4.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00
  4.0000e+01 0.0000e+00]
 [9.0000e+01 9.0000e+00 2.0000e+00 1.0000e+00 0.0000e+00 2.2060e+03
  

b.Add all the working hours(working hours is the column with index 6) of 'senior_citizens' and store it in a variable called 'working_hours_sum'

In [63]:
working_hours_sum =sum(senior_citizens[:,6])
working_hours_sum 


1917.0

c.Find the length of 'senior_citizens' and store it in a variable called 'senior_citizens_len'

In [65]:
senior_citizens_len= len(senior_citizens)
senior_citizens_len

61

d. Finally find the average working hours of the senior citizens by dividing 'working_hours_sum' by 'senior_citizens_len' and store it in a variable called 'avg_working hours'.

In [67]:
avg_working_hours = working_hours_sum/senior_citizens_len
avg_working_hours

31.42622950819672

e. Print 'avg_working_hours' and see if the govt. policy is followed.

In [70]:
print("Average Working Hour:", avg_working_hours)
if avg_working_hours > 25:
  print('the policy is not followed')
else:
  print('policy is followed')



Average Working Hour: 31.42622950819672
the policy is not followed


# Step 6: Let's check that higher educated people have better pay in general.

Create two new subset arrays called 'high' and 'low' by filtering 'census' according to education-num>10 and education-num<=10 (education-num is the column with index 1) respectively.



In [72]:
high = final_data[final_data[:,1]>10]

low = final_data[final_data[:,1]<=10]


Find the mean of income column(income is the column with index 7) of 'high' array and store it in 'avg_pay_high'. Do the same for 'low' array and store it's mean in 'avg_pay_low'.

In [77]:
avg_pay_high=  high[:,7].mean()
print("Average Pay for Higher Educated People",round(avg_pay_high,2))

Average Pay for Higher Educated People 0.43


In [79]:
avg_pay_low = low[:,7].mean()
print('average pay for low educated people',round(avg_pay_low,2))

average pay for low educated people 0.14
